### ISSUE TITLE
Create new committee accounts and replace test users' committee accounts

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#206]
**TASKS:** 

1. Create new committee accounts using Form 1 process on test server
2. Replace the terminated committee accounts currently used by the test users with fabricated committee accounts created in the FEC test environment. 
3. The new committee IDs should be applied across all FECFile Online environments - DEV, STAGE, and PROD.

**DEV Notes**
The authentication_account.cmtee_id and committee_accounts.committee_id fields will need to be updated to match the new committee account ids for each user.

See the last 2 entries of this document for instruction on how to set up test committee accounts: https://docs.google.com/document/d/1_WXGYoVeUztF5kNKMt-NMmX-eSETN8I4uzHOU97FrmQ

Users to update with old terminated committee account ids:

- [x] swise+1@tygart.com (New Committee ID: C00100495) - Please Do Not removed my Committee ID C00277608 currently using on Stage and DEV for testing. 
- [x] mitchell.jarrett@tcg.com, C00277616 (New Committee ID: C00100263)
- [x] aurelia.khorsand@tcg.com, C00277673 (New Committee ID: C00100503)
- [x] mary.honard@tcg.com, C00277863 (New Committee ID: C00100479)
- [x] todd.lees@tcg.com, C00771964 (New Committee ID: C00100461)
- [x] elaine.krauss@tcg.com, C00707398 (New Committee ID: C00100297)
- [x] david.heitzer@tcg.com, C00693044 (New Committee ID: C00100289)
- [x] matt.travers@tcg.com, C00776013 (New Committee ID: C00100230)
- [x] gregg.moreland@tcg.com, C00699124 (New Committee ID: C00100487)

### QA Notes
Each user listed above is given the test credentials necessary to use the test WebPrint and WebUpload services from EFO.
This process will result in a "clean slate" within committee accounts.

**Comment by WiseQA** [comment]
@MitchellTCG @mjtravers These committee accounts being created to test WebPrint and WebUpload services from EFO.   Can I still keep by committee ID I am using now to test on Stage and DEV please.

**Comment by dheitzer** [comment]
When I follow the instructions to create a test account, I get an endless spinning circle after hitting 'submit'

![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/1008a4c4-f23a-4689-ab4b-0b7caeb14741)

**Comment by dheitzer** [comment]
Reached out to Mahi and he is investigating.

**Comment by dheitzer** [comment]
Getting the following error that looks to be on the FEC side when testing this in DEV:

12:54:42.810: [APP/PROC/WEB.0] [2023-02-01 12:54:42,809: ERROR/ForkPoolWorker-7] Task fecfiler.web_services.tasks.submit_to_fec[0abd84a2-2c41-4f51-83ce-c8ae9f2f6d31] raised unexpected: Fault('CallableStatementCallback; uncategorized SQLException for SQL [{call efo.pkg_parser_util.get_status(?, ?)}]; SQL state [72000]; error code [4063]; ORA-04063: package body "EFO.PKG_PARSER_UTIL" has errors\nORA-06508: PL/SQL: could not find program unit being called: "EFO.PKG_PARSER_UTIL"\nORA-06512: at line 1\n; nested exception is java.sql.SQLException: ORA-04063: package body "EFO.PKG_PARSER_UTIL" has errors\nORA-06508: PL/SQL: could not find program unit being called: "EFO.PKG_PARSER_UTIL"\nORA-06512: at line 1\n')
12:54:42.810: [APP/PROC/WEB.0] Traceback (most recent call last):
12:54:42.810: [APP/PROC/WEB.0] File "/home/vcap/deps/0/python/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
12:54:42.810: [APP/PROC/WEB.0] R = retval = fun(*args, **kwargs)
12:54:42.810: [APP/PROC/WEB.0] File "/home/vcap/deps/0/python/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
12:54:42.810: [APP/PROC/WEB.0] return self.run(*args, **kwargs)
12:54:42.810: [APP/PROC/WEB.0] File "/home/vcap/app/django-backend/fecfiler/web_services/tasks.py", line 88, in submit_to_fec
12:54:42.810: [APP/PROC/WEB.0] submission_response_string = submitter.submit(dot_fec_bytes, submission_json)
12:54:42.810: [APP/PROC/WEB.0] File "/home/vcap/app/django-backend/fecfiler/web_services/dot_fec/dot_fec_submitter.py", line 45, in submit
12:54:42.810: [APP/PROC/WEB.0] response = self.fec_soap_client.service.upload(json_payload, dot_fec_bytes)
12:54:42.810: [APP/PROC/WEB.0] File "/home/vcap/deps/0/python/lib/python3.8/site-packages/zeep/proxy.py", line 46, in __call__
12:54:42.810: [APP/PROC/WEB.0] return self._proxy._binding.send(
12:54:42.810: [APP/PROC/WEB.0] File "/home/vcap/deps/0/python/lib/python3.8/site-packages/zeep/wsdl/bindings/soap.py", line 135, in send
12:54:42.810: [APP/PROC/WEB.0] return self.process_reply(client, operation_obj, response)
12:54:42.810: [APP/PROC/WEB.0] File "/home/vcap/deps/0/python/lib/python3.8/site-packages/zeep/wsdl/bindings/soap.py", line 229, in process_reply
12:54:42.810: [APP/PROC/WEB.0] return self.process_error(doc, operation)
12:54:42.810: [APP/PROC/WEB.0] File "/home/vcap/deps/0/python/lib/python3.8/site-packages/zeep/wsdl/bindings/soap.py", line 329, in process_error
12:54:42.810: [APP/PROC/WEB.0] raise Fault(
12:54:42.810: [APP/PROC/WEB.0] zeep.exceptions.Fault: CallableStatementCallback; uncategorized SQLException for SQL [{call efo.pkg_parser_util.get_status(?, ?)}]; SQL state [72000]; error code [4063]; ORA-04063: package body "EFO.PKG_PARSER_UTIL" has errors
12:54:42.810: [APP/PROC/WEB.0] ORA-06508: PL/SQL: could not find program unit being called: "EFO.PKG_PARSER_UTIL"
12:54:42.810: [APP/PROC/WEB.0] ORA-06512: at line 1
12:54:42.810: [APP/PROC/WEB.0] ; nested exception is java.sql.SQLException: ORA-04063: package body "EFO.PKG_PARSER_UTIL" has errors
12:54:42.810: [APP/PROC/WEB.0] ORA-06508: PL/SQL: could not find program unit being called: "EFO.PKG_PARSER_UTIL"
12:54:42.810: [APP/PROC/WEB.0] ORA-06512: at line 1

--
David Heitzer, Software Engineer
TCG, Inc. - Positively Distinct - CMMI-DEV Level 3 - CMMI-SVC Level 3 - ISO 9001:2015
Tel: 202-986-5533 x8589 | Mobile: 817-521-2197 | david.heitzer@tcg.com | www.tcg.com
  Linkedin

**Comment by dheitzer** [comment]
Mahi fixed the issue and I am now able to file in DEV using my account with a committee id created in testefo.

**Comment by dheitzer** [comment]
Changes made to support filing in DEV/STAGE without access to test-efo committee lookup functionality by stubbing the teset-efo accounts and using these for the lookup.  Discussed the implementation with developers today and made changes per this.  Currently testing+writing unit tests.

**Comment by dheitzer** [comment]
Placed back into CR for changes to populate account-info page with stubbed committee data.

**Comment by dheitzer** [comment]
Assigned team emails to committee ids as discussed in both test-efoservices and dummy data.

**Comment by dheitzer** [comment]
Changes to stub committee accounts data to match what was created in testefo has been made

**Comment by dheitzer** [comment]
All test-efo committees listed above have been updated with the assignee's email address.  This should conclude the setup of these test accounts.  Note: the following are spare accounts created in test-efo in case we need them (they would need their email addresses updated in test-efo as well once assigned):

TEST_COMMITTEE_NAME18
C00100511

TEST_COMMITTEE_NAME19
C00100529

TEST_COMMITTEE_NAME20
C00100537

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review is a verbal from DEV.   Committee IDs have been assigned and validated as accessible by each end user.  (Note:   As denoted above QA will keep old and new committee ID accounts).

QA Review Completed.   Moved to Stage Ready.
