### ISSUE TITLE
Create Django model for contacts

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#34]
Currently, the contact data is stored in the "entity" table and also has the view "all_contacts_view" associated with it.

**Tasks**
- [x] Create a single "contacts" model that holds all 4 types of contacts using the utility script that generates models from the validation schema. (Probably run the utility script against the validation schema that has the most properties and then hand enter the rest of the properties needed by the other schemas)
- [x] Additional fields: created(timestamp), updated(timestamp), deleted(timestamp)
- [x] Model should have CRUD functionality
- [x] unit tests
- [x] code documentation
- [x] informative logging

**Acceptance Criteria**
- [x] unit tests pass in CircleCI

**QA**
Passing unit tests: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/169/workflows/ee822112-a3b7-4e5c-a7e5-5b2f8f2f0e48/jobs/417

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/9/22:** Four schemas will be captured in one table. This has already been done for Schedule A and Form 3X. Pointed at 5.

**Comment by toddlees** [comment]
Ready for CR

**Comment by WiseQA** [comment]
Verified unit test passed successfully as denoted in Acceptance Criteria.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/645109ab-9b00-4c97-ad23-5c2b61877493)

QA review completed.  Moved to Stage Ready.
