### ISSUE TITLE
Import UAT data from AWS into cloud.gov

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#37]
So that the team has the best test data, we should import the data from the UAT site from AWS into cloud.gov. We should also make sure we have the right database size for the next year or so.

**Task**
Create a Postgres dump in SQL format from the TCG AWS subscription of the UAT front-end database that is currently saved in a snapshot. Use that SQL dump file to recreate databases in the 3 Cloud.gov spaces

**Acceptance Criteria**
- [x] Can log into the development app using UAT credentials
- [x] Can log into the stage app using the UAT credentials
- [x] Can log into the production app using the UAT credentials

**Comment by lbeaufort** [comment]
FYI, here's a mapping of RDS service sizes and AWS machine instances. This is for new services: https://github.com/cloud-gov/aws-broker/blob/master/catalog-template.yml

 cloud.gov also recently added the ability to increase the service type with minimal downtime (~15-20 min): https://cloud.gov/docs/services/relational-database/#update-an-instance

**Comment by mjtravers** [comment]
@lbeaufort Here's the AWS page that lists the details of the instance types:

https://aws.amazon.com/ec2/instance-types

For example, the t3.small has 2 CPUs and 2GB RAM. I'm thinking 8GB RAM would be the lower bound and 2 CPUs are probably fine as we're the only ones that are going to be using the site in the short term so perhaps start off with the instanceClass: db.m5.large?

**Comment by lbeaufort** [comment]
> @lbeaufort Here's the AWS page that lists the details of the instance types:
> 
> https://aws.amazon.com/ec2/instance-types
> 
> For example, the t3.small has 2 CPUs and 2GB RAM. I'm thinking 8GB RAM would be the lower bound and 2 CPUs are probably fine as we're the only ones that are going to be using the site in the short term so perhaps start off with the instanceClass: db.m5.large for fecfile-web-api?

@mjtravers thank you for your research. Based on the cloud.gov mapping I linked above, we should go with `medium-gp-psql-redundant` in cloud.gov to get `db.m5.large`.

**Comment by WiseQA** [comment]
Verify login to DEV using UAT credentials
https://fecfile-web-app-dev.app.cloud.gov/
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/6dd79f03-c5e4-4efe-ac5c-88584672ce3e)

**Comment by mjtravers** [comment]
Shelly, I looked into why Ryan's account does not have all the records that the UAT server has and found that much of the data in the UAT database from Ryan was created after Oct. 19, 2021, which is the date the database snapshot was made and given to us. Records prior to that date are in the Cloud.gov databases that populated with the 10/19/2021 snapshot.
I am sending this ticket back to QA with that new understanding.
