### ISSUE TITLE
Create Django app for Schedule D

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#483]
The Schedule D data needs to have its datbase table and REST API endpoints created in the Django app backend. The app setup will be similar to the same setup created for the Schedule B data.

**Tasks**

- [x] Create child schedule D table and app whose parent is the main transaction app
- [x] Add necessary unit tests
- [x] Create URL endpoints to access records from REST API

**QA Notes**
see comment below with unit tests passing

**Comment by Elaine-Krauss-TCG** [comment]
Unit tests passing
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/4d8d6ea8-31f4-4a0e-821e-d219eebb5149)

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

**Comment by mjtravers** [comment]
Unit test report found here: https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2179/workflows/140e9d62-11d0-479a-aceb-e5246045f81e/jobs/6933

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in app.circleci per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/87a80050-eff2-4b93-9a19-5d73cfd174ad)

QA Review Completed. Moved to Stage Ready,
