### ISSUE TITLE
Create new Committee for Ryan for the May 8th Commissioner Demo and add mock committee detail data to s3

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-web-api#789]
### Purpose:
Create a new committee on all three environments (DEV, STAGE, & PROD) for Ryan Lanz that most approximates an actual Form 3X committee.  Please add this (and all the other committee detail data) to the s3 bucket so it can be updated as needed.

DEV Notes
Move the mocked committee information pulled from the openfec/test_efo_mock_data/committee_accounts.json file into the appropriate s3 bucket and update the api to retrieve this on committee detail lookup of mocked data.

See here for details on mock_openfec:
https://github.com/fecgov/fecfile-web-api/blob/develop/django-backend/fecfiler/mock_openfec/README.md

Also 1) run load_committee_details command with s3 flag and 2) add new committee id to ids to override environment variable.  Do after deploy in:
- [x] DEV
- [x] STAGE
- [x] PROD

QA Notes
Screenshots of mock data pulled from API showing mock data used in committee banner.

### Tasks
Move the mocked committee detail data into an s3 bucket
Create a new committee in triplicate 
- [x] created on DEV
- [ ] created on STAGE
- [ ] created on PROD
- [ ] Please associate committees with his Login.gov email: rlanz@fec.gov

Ryan already created the committee with EFO on test please verify the information below matches the information you pull
- [x] FEC ID: C00101303
- [x] Committee Name: The Leadership PAC
- [x] Filing Frequency: Monthly
- [x] Status: Active (Hard code if needed)
- [x] Committee Type in Application: PAC - Nonqualified - Leadership PAC
- [x] Committee Designation in Database: D - Leadership PAC
- [x] Committee Type in Database: N - Non-Qualified Non-Party

**Comment by MitchellTCG** [comment]
@dheitzer Can you add the submission password you created into this ticket

**Comment by mjtravers** [comment]
Passes CR. Sending to QA. For testing, ticket passes if a user sees committee information in the page banner and in the Account page.

Here are the passing unit tests:


![Image](https://github.com/fecgov/fecfile-web-api/assets/2971785/76beeeec-caa1-444b-b3ab-dd4c47ed1673)

**Comment by MitchellTCG** [comment]
@RyanLanz 
Please verify your committee works on Stage and Prod.

**Comment by MitchellTCG** [comment]
### Passed
I verified with Ryan at 10 am on Friday April 26th that all three of his environments work as expected

**Comment by WiseQA** [comment]
No QA review needed on this ticket. 

Moved to Stage Ready.
